### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 1337-ishaan**
# Description

Fixed typo for installation of `yarn`

---

## PR-Codex overview
This PR updates the package name in the README.md file.

### Detailed summary
- Updated package name from `@rmrk-team/evm-contract` to `@rmrk-team/evm-contracts` in the README.md file.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by ThunderDeliverer — APPROVED** [review]
Thank you for catching this!

**Review by ThunderDeliverer — CHANGES_REQUESTED** [review]
Could you please rebase your branch to the dev branch? I was unable to push the rebased branch since it's in your own repository.

**Comment by 1337-ishaan** [comment]
#221

**Comment by 1337-ishaan** [comment]
Rebased into dev in #222, hence closing this.

**Pull request closed without merging**
