### PR TITLE
A simple script to generate abis jsons from implementation contracts

### PR DESCRIPTION
**Pull request by Yuripetusko**
A simple script to generate abis jsons from implementation contracts

### CODE REVIEW

**Comment by CicadaNCR** [comment]
Seems fine on its face -- any reason in particular you're writing them to `/artifacts/abis/implementations/` instead of just loading them directly?

**Comment by Yuripetusko** [comment]
> Seems fine on its face -- any reason in particular you're writing them to `/artifacts/abis/implementations/` instead of just loading them directly?

Directly like where? I'm open to suggestions of a better directory to save them to. For now I just copy and paste the whole folder to the Singular codebase, so it's easy for me to do it if they are all written in the same dir

**Comment by CicadaNCR** [comment]
> 

That makes sense, I'll merge since it's just a utility script anyway. By default you can find the generated ABIs their *.sol folder under the contracts directory, Nesting for example:

`artifacts/contracts/implementations/RMRKNestingImpl.sol/RMRKNestingImpl.json`

I realize walking the tree could be a PITA, so as a utility script that runs automagic on some other action, is all good.

**Comment by Yuripetusko** [comment]
Yeah I cannot simply see these files in viewer,. only when I inspection sol files with code is when I see json files, so this seemed like an easy option

**Pull request merged**
