### PR TITLE
Royalties splitter

### PR DESCRIPTION
**Pull request by steven2308**
# Description

Adds RoyaltiesSplitter contract.
Beneficiaries and shares are set on creation and cannot be further changed.
Native tokens received are immediately distributed.
ERC20 tokens do not notify the receiver, so they must be manually claimed. To simplify the logic, the distribute method can be called by anyone and it will distribute to all beneficiaries according to the shares.

# Checklist

- [x] Verified code additions
- [x] Updated NatSpec comments (if applicable)
- [x] Regenerated docs
- [x] Ran prettier
- [x] Added tests to fully cover the changes

---

### Detailed summary
- Added `RMRKRoyaltiesSplitter` smart contract for sharing royalties from native or ERC20 payments.
- Added `distributeERC20` function to distribute ERC20 payments to beneficiaries.
- Added `getBenefiariesAndShares` function to get the list of beneficiaries and their shares.
- Added `ERCPaymentDistributed` and `NativePaymentDistributed` events.
- Added error types `InvalidInput`, `FailedToSend`, and `OnlyBeneficiary`.
- Added tests for the `RMRKRoyaltiesSplitter` contract.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Swader** [comment]
What if the artists have a falling out, or the collection is sold, and there is a need to change one of the recipients? Or is this a separate tool that is set as the royalty recipient, and then middleman style distributes the funds?

**Comment by steven2308** [comment]
> What if the artists have a falling out, or the collection is sold, and there is a need to change one of the recipients? Or is this a separate tool that is set as the royalty recipient, and then middleman style distributes the funds?

In that case you would simply deploy a new splitter and update the royalties recipient on the collection. The collection owner still holds the keys and could update the recipient any time, so this requires trust on them, unless it's owned by a multisig.

**Comment by Swader** [comment]
Yep, makes sense, all good then.

**Review by ilionic — APPROVED** [review]

**Comment by ilionic** [comment]
Would be good to add additional distribution gating mechanics, ie restricting to beneficiaries

**Comment by steven2308** [comment]
> Would be good to add additional distribution gating mechanics, ie restricting to beneficiaries

Now only beneficiaries can init the distribution for ERC20s

**Pull request merged**
