### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by steven2308**
Merge after publishing v1.2.0.

# Checklist

- [x] Verified code additions
- [x] Updated NatSpec comments (if applicable)
- [x] Regenerated docs
- [x] Ran prettier
- [x] Added tests to fully cover the changes

---

## PR-Codex overview
This PR updates the `@rmrk-team/evm-contracts` package to version `1.2.1` and includes changes such as updating the `IERC6454beta` interface to `IERC6454`, adding a new function to withdraw minting proceeds, and adding new error messages. 

### Detailed summary
- Updated package version to `1.2.1`
- Updated `IERC6454beta` interface to `IERC6454`
- Added a new function `withdrawRaisedERC20` to withdraw minting proceeds
- Added new error messages

> The following files were skipped due to too many changes: `docs/implementations/premint/RMRKEquippableImplPreMint.md`, `docs/implementations/premint/RMRKMultiAssetImplPreMint.md`, `test/implementations/equippable.ts`, `docs/implementations/abstracts/RMRKAbstractEquippableImpl.md`, `docs/implementations/abstracts/RMRKAbstractMultiAssetImpl.md`, `docs/implementations/nativeTokenPay/RMRKExternalEquipImpl.md`, `docs/implementations/nativeTokenPay/RMRKNestableMultiAssetImpl.md`, `docs/implementations/premint/RMRKNestableMultiAssetImplPreMint.md`, `docs/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.md`, `test/implementations/externalEquippable.ts`, `hardhat.config.ts`, `contracts/implementations/nativeTokenPay/RMRKExternalEquipImpl.sol`, `contracts/RMRK/extension/soulbound/RMRKSoulbound.sol`, `scripts/deploy_bulkWriter.ts`, `contracts/implementations/abstracts/RMRKAbstractEquippableImpl.sol`, `contracts/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.sol`, `contracts/implementations/abstracts/RMRKAbstractMultiAssetImpl.sol`, `scripts/generate_abis.ts`, `docs/RMRK/utils/RMRKBulkWriter.md`, `test/renderUtils.ts`, `docs/implementations/erc20Pay/RMRKMultiAssetImplErc20Pay.md`, `docs/implementations/erc20Pay/RMRKEquippableImplErc20Pay.md`, `test/implementations/lazyMintErc20Pay.ts`, `docs/implementations/erc20Pay/RMRKNestableMultiAssetImplErc20Pay.md`, `test/extensions/soulbound.ts`, `docs/RMRK/utils/RMRKNestableRenderUtils.md`, `docs/RMRK/utils/RMRKEquipRenderUtils.md`, `contracts/RMRK/utils/RMRKNestableRenderUtils.sol`, `contracts/RMRK/utils/RMRKBulkWriter.sol`, `contracts/RMRK/equippable/RMRKMinifiedEquippable.sol`, `test/bulkWriter.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by steven2308** [comment]
@ThunderDeliverer  could you give a try at fixing this mess with master branch.
We should always be able to rebase :sweat:

**Comment by ThunderDeliverer** [comment]
> @ThunderDeliverer could you give a try at fixing this mess with master branch.
We should always be able to rebase 😓

I rebased the branch and that produced no errors, so the conflicts were due to stale commits.
I also added exception that allows us to force push to `dev`.

Additionally, I think we should nuke `dev` every time we merge it to `master` and branch out of `master` to a new `dev` at that point 🤔 The issue we are facing is due to the merge commits in `master` that `dev` is missing. Alternatively, we could try rebasing `dev` after every merge..

**Comment by steven2308** [comment]
Maybe nuking dev once would be enough? It would be too much for me to do it every time

**Comment by ThunderDeliverer** [comment]
> Maybe nuking dev once would be enough? It would be too much for me to do it every time

No, the branches diverge after every merge to master, so we need to address this every time.

**Pull request merged**
